version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - "gunicorn"
      - "reciepts.wsgi:application"
      - "--bind"
      - "0.0.0.0:8080"
    ports:
      - "8000:8080"
    restart: "always"
    env_file:
      - ".env"
    volumes:
      - "./reciepts/database:/app/database"